language: node_js
node_js: 
  - "stable"

cache: 
  dependencies:
    node_modules

script:
  - npm install
  - npm build
  - CI=false npm run build 

deploy:
  provider: surge
  skip_cleanup: true
  domain: http://aliraza-portfolio.surge.sh/
  project: ./build/

on: 
  branch: main